timestamp
20-AUG-19 07.23.18.217000 PM

-- alter generated idendity by jpa 
ALTER TABLE address MODIFY address_id GENERATED BY DEFAULT ON NULL AS IDENTITY;
ALTER TABLE cart MODIFY cart_id GENERATED BY DEFAULT ON NULL AS IDENTITY;
ALTER TABLE cart_line MODIFY cart_line_id GENERATED BY DEFAULT ON NULL AS IDENTITY;
ALTER TABLE product MODIFY cart_id GENERATED BY DEFAULT ON NULL AS IDENTITY;
ALTER TABLE customer MODIFY customer_id GENERATED BY DEFAULT ON NULL AS IDENTITY;

-- alter table identity
alter table orders add order_id_new number(19) generated by default on null as identity;
update orders set order_id_new = order_id;

-- created
ALTER TABLE table MODIFY time_collumn TIMESTAMP DEFAULT CURRENT_TIMESTAMP;


-- auto detect last
ALTER TABLE cart MODIFY cart_id
GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH LIMIT VALUE);

-- cascade constraint
truncate table orders CASCADE CONSTRAINTS ;
select 'alter table '||a.owner||'.'||a.table_name||' disable constraint '||a.constraint_name||';'
from all_constraints a, all_constraints b
where a.constraint_type = 'R' and a.status='ENABLED'
and a.r_constraint_name = b.constraint_name
and a.r_owner  = b.owner
and b.table_name = upper('YOUR_TABLE');



-- insert with single quote
insert into product (headline, product_desc, product_name, price) VALUES ('1', 'gamis syar''i','gamis syari', '190000');

UPDATE product REPLACE(image, '2', '3');

UPDATE product SET img_full = REPLACE(img_full, 'https', 'http');
UPDATE product SET img_mid = REPLACE(img_mid, 'https', 'http');
UPDATE product SET img_thumb = REPLACE(img_thumb, 'https', 'http');

-- better view on sql command
-- set wrap off 

-- list all users
SELECT username FROM dba_users

-- check current user
select sys_context( 'userenv', 'current_schema' ) from dual;

-- drop column table
ALTER TABLE product_variant DROP COLUMN PRODUCT_VARIANT_PRODUCT_VARIANT_ID;

-- reset idendity to 1
ALTER TABLE category MODIFY(category_id GENERATED AS IDENTITY (START WITH 1));

ALTER TABLE member MODIFY(member_id GENERATED AS IDENTITY (START WITH 1));

ALTER TABLE cart MODIFY(cart_id GENERATED AS IDENTITY (START WITH 1));
ALTER TABLE cart_line MODIFY(cart_line_id GENERATED AS IDENTITY (START WITH 1));

ALTER TABLE address MODIFY(address_id GENERATED AS IDENTITY (START WITH 1));

ALTER TABLE customer MODIFY(customer_id GENERATED AS IDENTITY (START WITH 23));

ALTER TABLE VARIANT_VALUE MODIFY(VARIANT_VALUE_ID GENERATED AS IDENTITY (START WITH 1));

-- find select incase sensitive
select * from my_table where regexp_like(column_1, '^my_string$', 'i');

select * from city where regexp_like(city_name, 'purwakarta', 'i');

select * from villages ORDER BY id DESC FETCH FIRST 5 ROWS ONLY;

select * from city where regexp_like(city_name, 'jakarta', 'i') FETCH FIRST 1 ROWS ONLY;

select * from city where regexp_like(city_name, 'jakarta', 'i') and ROWNUM <= 1;

select CASE WHEN MAX(city_id) IS NULL THEN 'FALSE' ELSE 'TRUE' END User_exists from city where regexp_like(city_name, 'purwakarta', 'i') and ROWNUM <= 1

-- Get User List All Table
SELECT table_name FROM user_tables

-- Get Table DDL
select dbms_metadata.get_ddl('TABLE', 'product') from dual;
desc product;

-- select last row
select * from table_name ORDER BY primary_id DESC FETCH FIRST 1 ROWS ONLY;


-- expdp
expdp scott/tiger@ora19.haidar.id:1521/orclpdb.haidar.id tables=EMP,DEPT directory=TEST_DIR dumpfile=EMP_DEPT.dmp logfile=expdpEMP_DEPT.log
-- expdp ecommerce/B235z1l051i1@haidar.tech:1521/xepdb1 directory=dump_dir dumpfile=znb_reg_schema.dmp logfile=import_znb.log remap_schema=znb:ecommerce
impdp ecommerce/B235z1l051i1@haidar.tech:1521/xepdb1  directory=dump_dir dumpfile=znb_reg_schema.dmp logfile=haidar_import.log remap_schema=znb:ecommerce
impdp \"sys/4l4h3D077003@//haidar.tech:1521/xepdb1 as sysdba\"  directory=dump_dir dumpfile=znb_reg_schema.dmp logfile=haidar_import.log remap_schema=znb:ecommerce
100792
DJ0703

-- load data from external
SELECT * FROM   EXTERNAL (   
    (time_id        DATE NOT NULL,     
     prod_id        INTEGER NOT NULL,
     quantity_sold  NUMBER(10,2),
     amount_sold    NUMBER(10,2))     
    TYPE ORACLE_LOADER     
    DEFAULT DIRECTORY data_dir1
    ACCESS PARAMETERS (
      RECORDS DELIMITED BY NEWLINE
      FIELDS TERMINATED BY '|')     
   LOCATION ('sales_9.csv') REJECT LIMIT UNLIMITED) sales_external;
   
   
-- DROP ALL TABLES
BEGIN

  --Bye Tables!
  FOR i IN (SELECT ut.table_name
              FROM USER_TABLES ut) LOOP
    EXECUTE IMMEDIATE 'drop table '|| i.table_name ||' CASCADE CONSTRAINTS ';
  END LOOP;

END;



-- --  KONI JABAR

select ID,
       NAMA,
       PA_PI,
       STATUS,
       CABANG_OLAHRAGA,
       KATEGORI
  from ATLET WHERE KATEGORI='BELA DIRI'

select ID,
       NAMA,
       PA_PI,
       STATUS,
       CABANG_OLAHRAGA,
       KATEGORI
  from ATLET WHERE ID = 10
:P15_ID


SELECT CABANG_OLAHRAGA, 
COUNT(ID) total 
from atlet
where kategori='TERUKUR'
 group by  CABANG_OLAHRAGA ;

select COUNT(ID), CABANG_OLAHRAGA, MAX(kategori) From atlet 
GROUP BY CABANG_OLAHRAGA;

SELECT * FROM ATLET
WHERE ID  < 156
ORDER BY ID;

select COUNT(ID), MAX(CABANG_OLAHRAGA), kategori From atlet 
GROUP BY kategori;

SELECT 
ID_AGENDA,
HARI,
TANGGAL,
WAKTU,
AGENDA,
TEMPAT,
PELAKSANA,
KETERANGAN
 FROM AGENDA_KETUM 
WHERE ID_AGENDA = : P12_ID_AGENDA 


declare

 cursor atlet is
   select status, nama
     from atlet
    where rownum < 5;
 
begin
  sys.htp.p('<ul>');
  for a in atlet loop
    sys.htp.p('<li>' || a.status || ' (' || a.nama || ')</li>' );
   end loop;
  sys.htp.p('</ul>');
end;

begin
  sys.htp.p('
<div class="dm-ContentWell">
<dl class="t-AVPList  t-AVPList--leftAligned">
    <dt class="t-AVPList-label">
        Cabor
    </dt>
    <dd class="t-AVPList-value">
        Cabang Olahraga
    </dd>
    <dt class="t-AVPList-label">
        Tempat Latihan
    </dt>
    <dd class="t-AVPList-value">
        Gor Sasakawa
    </dd>
    <dt class="t-AVPList-label">
        Penginapan Atlet
    </dt>
    <dd class="t-AVPList-value">
        Mess Prestasi 
    </dd>
    <dt class="t-AVPList-label">
        Venues PON XX
    </dt>
    <dd class="t-AVPList-value">
        Jaya Pura
    </dd>
    <dt class="t-AVPList-label">
        Waktu Pelaksanaan
    </dt>
    <dd class="t-AVPList-value">
        Oktober 2020
    </dd>
</dl>
</div>');
end;

begin
  sys.htp.p('<div class="dm-ContentWell">
<dl class="t-AVPList  t-AVPList--leftAligned">
    <dt class="t-AVPList-label">
        Cabor
    </dt>
    <dd class="t-AVPList-value">
        ' || 'haidar' || '
    </dd>');
end;

UPDATE atlet set kategori = 'BEREGU' WHERE ID > 156 AND ID < 300;


if V('APP_USER') = 'KETUM' then
  return 'f?p=123:4:&SESSION.';
else
  return 'f?p=123:10:&SESSION.'; -- send the user back to the login page.
end if;

if :P_UNAME = 'ketum' then
  return 'f?p=123:4:&SESSION.';
else
  return 'f?p=123:13:&SESSION.'; -- send the user back to the login page.
end if;



if V('APP_USER') = 'KETUM' then
  return 'f?p=123:4:&SESSION.'; 
else
  return 'f?p=123:13:&SESSION.'; -- send the user back to the login page.
end if;
