#!/bin/sh
unset SESSION_MANAGER
exec sh $HOME/.xinitrc
[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
#exec dwm
xsetroot -solid grey
vncconfig -iconic &
x-terminal-emulator -geometry 1024x768+10+10 -ls -title "$VNCDESKTOP Desktop" &
exec dwm